language: node_js

node_js:
- '8.10'

before_install:
- export TZ=Asia/ShangHai

install:
- npm install -g hexo
- npm install -g hexo-cli
- npm install -g hexo-deployer-git
- npm install -g hexo-generator-archive
- npm install -g hexo-generator-category
- npm install -g hexo-generator-feed
- npm install -g hexo-generator-index
- npm install -g hexo-generator-sitemap
- npm install -g hexo-generator-tag
- npm install -g hexo-renderer-ejs
- npm install -g hexo-renderer-jade
- npm install -g hexo-renderer-marked
- npm install -g hexo-renderer-sass
- npm install -g hexo-renderer-stylus
- npm install -g hexo-search
- npm install -g hexo-server

script:
# 初始化 GIT
- git config --global user.name "$GIT_NAME"
- git config --global user.email "$GIT_EMAIL"
- git config --global push.default simple

# 更新
- git checkout master
- git pull origin master

# 生成
- hexo generate

# 把 docs 发布出去
- git add --all .
- MESSAGE=`date +\ %Y-%m-%d\ %H:%M:%S`
- git commit -m "Site updated:$MESSAGE"
# - git push --force "https://${GH_TOKEN}@${GH_REF}" origin master
# - git push origin master
- git push "https://${GH_TOKEN}@${GH_REF}" master:master
