language: node_js

node_js:
- '>5.1'

before_install:
- export TZ=Asia/ShangHai

install:
- npm install
- npm install -g hexo-cli

script:
# 初始化 GIT
- git config --global user.name "$GIT_NAME"
- git config --global user.email "$GIT_EMAIL"
- git config --global push.default simple

# 更新
- git checkout master
- git pull origin master

# 生成
- hexo generate

# 把 docs 发布出去
- git add --all .
- MESSAGE=`date +\ %Y-%m-%d\ %H:%M:%S`
- git commit -m "Site updated:$MESSAGE"
# - git push --force "https://${GH_TOKEN}@${GH_REF}" origin master
# - git push origin master
- git push "https://${GH_TOKEN}@${GH_REF}" master:master
