language: node_js
node_js:
- '5.1'
env:
  global:
  - secure: long secure base64 string
  - secure: XSd9+/9PFd5LJ9fSnLQ3od7+fYM4gBIsm+Kzd4YZe3n7a+1Tuf+MzSbAOMViNaVdGMPRi4RY38oVSXSKVYzwmtd26M0SYpqL7qENUDKgyCLTm21bxUXVZ8ikv6478/ifGqXmI7Hal/ycH9rMR3tNKxImZ/+9T8ttyNXDM3HIyvc0YIaR9BIot+u1xJDNQAhaecyzISGn6fhfBscr41ftMWI1I5okZGkUDM1n0gHy6oaiVamLKJo+sttzXTKagLlS4bQjJnmPs49bzj3sd8vAaqehSdyII122/dfJojMFD+cwbgQCCs/AS/RChK1mnpxeOhskv7qF5SmwKuu/tjjK7r2lm82qiUflEa266Zc19AfqVOe0guclXjevtxqcvGywnVbVv86CbcIEtDhXqaB4XPGBtIn+ivJLuA5MJ9T07/guX1xNgdVJwr1iYtuGHGS/h3zvb2VSindORnjlRJCAr8D2xRNbyH/0TCLj3q3KxGWev3CnV8btEyv2t5rNwtNCnlE2YbMdO/PLKDyzNYb3aZcoKiNwEmXjbHxLb3x8bnLSo//Be+Dn9cGv/2rG5JeKP9RE4yXjDZTg9PeLAnMwfF4rfWpqMpA5K9Kg0wOYsA0XakEzrXUTcpw7hl0DS4Yk6D8L7/VBMF1Y/0xlOCq9vX0dqsf0m+dUS+pzpV6zodE=
before_install:
- export TZ=Asia/ShangHai
install:
- npm install
script:
- git config --global user.name "$GIT_NAME"
- git config --global user.email "$GIT_EMAIL"
- git config --global push.default simple
- git clone --depth 1 --branch gh-pages https://$GH_TOKEN@github.com/$GIT_NAME/$HEXO_BLOG
  public
- npm run generate
- cd public
- git add -A .
- MESSAGE=`date +\ %Y-%m-%d\ %H:%M:%S`
- git commit -m "Site updated:$MESSAGE"
- git push --quiet
