# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Dray's Home
subtitle: 疯狂痴呆傻，美甘苦涩禅。
keywords: dray,_0dc,we_get,疯,狂,痴,呆,傻,美,甘,苦,涩,禅,疯狂,痴呆,傻,美甘,苦涩,禅,疯狂痴呆傻,美甘苦涩禅
description: Dray's Blog
author: Dray
language: zh-CN
timezone: Asia/ShangHai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://idc.wf
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: category
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: fexo

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/DrayChou/Blog-Hexo
  branch: gh-pages

#disqus 论坛
disqus_shortname: weshome

feed:
  type: atom
  path: rss.xml
  limit: 20
  hub:


## 主题相关的配置
# Set avatar (Absolute url and relative url)
avatar: http://s.gravatar.com/avatar/00ced3a6cdfd0398fabe0717147a6a32?s=200

# Set favicon
favicon: /favicon.ico

home_nav:
  - name: Blog
    url: /archives
    target_blank: false #不在新页面打开
  - name: Project
    url: /project
    target_blank: false #不在新页面打开
  - name: Github
    url: "https://github.com/DrayChou/"
    target_blank: true  #在新页面打开

# config page nav
page_nav:
  - name: 博客
    url: /archives/
    target_blank: false # 不在新页面打开
  - name: 分类
    url: /category/
    target_blank: false
  - name: 标签
    url: /tags/
    target_blank: false
  - name: 友链
    url: /link/
    target_blank: false
  - name: 关于
    url: /about/
    target_blank: false
  - name: RSS
    url: "http://feeds.feedburner.com/WesHome"
    target_blank: true # 在新页面打开

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: true # true|fase

# 盒子
toolbox:
  isShow: true # true|fase
  text: 盒子

search_slogan:
  isShow: true # true|fase
  text: Can you find the bug of world ~

link_slogan:
  isShow: true # true|fase
  text: 交换友链可以邮件 i@idc.wf

# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true

# =========================================================
# 个性化设置
# =========================================================
# Custom CSS style
personal_style: /css/personal-style.css

home_background_scheme: light # dark、light

# custom font-family 暂时只支持这3种英文字体，你可以完全自定义字体(看文档)
blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV  # HOME_NAV | POST

# =========================================================
# 第三方服务
# =========================================================
# Stats
google_analytics:
baidu_analytics:

# =========================================================
# 页面内容设置
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "Dray Chou."
    - "喜欢看书，擅长编程，喜欢睡懒觉."
    - "PHP开发工程师."
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@draychou"
    text_value_url: https://github.com/draychou
  - type: mail
    icon: icon-mail
    text_key: Mail
    text_value: "i@idc.wf"
  - type: location
    icon: icon-location
    text_value: 魔都

link:
  - name: 方片子的博客
    info: 方片子的博客
    url: http://www.fangshanzi.com/
    avatar: http://fangshanzi.com/wp-content/themes/magicroller/images/logo.png
  - name: Locyoo Manor|部落格
    info: Locyoo Manor|部落格
    url: http://locyoo.com/blog/
    avatar: http://locyoo.com/blog/wp-content/uploads/2015/04/cooltext117007009229767.png
  - name: 方片快报
    info: 方片快报
    url: http://fpnews.cn/
    avatar: http://fpnews.cn/fpnews.png

project:
  - type:
    name: tgbot-php
    url: https://github.com/DrayChou/tgbot-php
    intro: 一个 PHP 写的 Telegram 机器人。
